# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param market market name 
#' @param data compressed data
#' @export 
NULL

R_decompress <- function(market, data) {
    .Call('decompress_R_decompress', PACKAGE = 'decompress', market, data)
}

